# 🦛 Chonkie Advanced Chunking Tutorial

Welcome to this comprehensive tutorial on **Chonkie** - a powerful open-source library for text chunking in RAG (Retrieval Augmented Generation) applications. This notebook explores various advanced chunking mechanisms and demonstrates how different strategies affect text segmentation.

## 📊 Overview Architecture

```mermaid
%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ff6b6b', 'primaryTextColor': '#fff', 'primaryBorderColor': '#ee5a52', 'lineColor': '#4ecdc4', 'secondaryColor': '#45b7d1', 'tertiaryColor': '#96ceb4', 'noteTextColor': '#2d3436', 'noteBkgColor': '#ffeaa7'}}}%%
graph TB
    A[📝 Input Text] --> B{Chunking Strategy}
    
    B --> C1[🔢 TokenChunker]
    B --> C2[📄 SentenceChunker]
    B --> C3[🔄 RecursiveChunker]
    B --> C4[🧠 SemanticChunker]
    B --> C5[⚡ LateChunker]
    B --> C6[💻 CodeChunker]
    
    C1 --> D1[Fixed Token<br/>Boundaries]
    C2 --> D2[Sentence<br/>Boundaries]
    C3 --> D3[Hierarchical<br/>Splitting]
    C4 --> D4[Semantic<br/>Similarity]
    C5 --> D5[Document-Level<br/>Context]
    C6 --> D6[AST-Based<br/>Structure]
    
    D1 --> E[📦 Chunked Output]
    D2 --> E
    D3 --> E
    D4 --> E
    D5 --> E
    D6 --> E
    
    E --> F[🎨 HTML Visualization]
    F --> G[Color-Coded Chunks]
    
    style A fill:#ff6b6b,stroke:#ee5a52,stroke-width:3px,color:#fff
    style B fill:#ffeaa7,stroke:#fdcb6e,stroke-width:3px
    style C1 fill:#74b9ff,stroke:#0984e3,stroke-width:2px,color:#fff
    style C2 fill:#a29bfe,stroke:#6c5ce7,stroke-width:2px,color:#fff
    style C3 fill:#fd79a8,stroke:#e84393,stroke-width:2px,color:#fff
    style C4 fill:#55efc4,stroke:#00b894,stroke-width:2px,color:#000
    style C5 fill:#ffeaa7,stroke:#fdcb6e,stroke-width:2px
    style C6 fill:#81ecec,stroke:#00cec9,stroke-width:2px
    style E fill:#dfe6e9,stroke:#b2bec3,stroke-width:3px
    style F fill:#fab1a0,stroke:#e17055,stroke-width:2px
    style G fill:#00b894,stroke:#00cec9,stroke-width:2px,color:#fff
```

## 🎯 What You'll Learn

This tutorial covers:
- **TokenChunker**: Fixed-size token-based chunking
- **SentenceChunker**: Sentence boundary-preserving chunks
- **RecursiveChunker**: Hierarchical recursive splitting
- **SemanticChunker**: Similarity-based semantic grouping
- **LateChunker**: Document-level contextual embeddings
- **CodeChunker**: AST-based code structure chunking

Each section demonstrates:
1. 📖 How the chunker works
2. ⚙️ Configuration parameters
3. 🔍 Effect on sample text
4. 🎨 Visual representation with color-coded chunks

## 📦 Installation and Setup

First, let's install Chonkie with all the advanced features we'll need.

In [1]:
# Install Chonkie with all advanced features
# This includes semantic, code, and visualization capabilities
# !pip install -q "chonkie[all,viz]"

# Import required libraries
from chonkie import (
    TokenChunker, 
    SentenceChunker, 
    RecursiveChunker, 
    SemanticChunker,
    LateChunker,
    CodeChunker,
    Visualizer
)
from IPython.display import HTML, display
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed
import warnings
warnings.filterwarnings('ignore')

print("✅ Chonkie and all dependencies installed successfully!")

✅ Chonkie and all dependencies installed successfully!


## 📚 Sample Text for Demonstration

We'll use a comprehensive sample text covering multiple topics to demonstrate how different chunking strategies affect the output. This text includes various themes: technology, climate change, and scientific discoveries.

In [27]:
sample_text = """
Artificial Intelligence and Machine Learning Revolution

The field of artificial intelligence has undergone tremendous transformation in recent years. Machine learning algorithms have become increasingly sophisticated, enabling computers to perform tasks that once seemed exclusively human. Deep learning, a subset of machine learning, uses neural networks with multiple layers to process complex patterns in data. These networks can recognize images, understand natural language, and even generate creative content.

The impact of AI extends across multiple industries. In healthcare, machine learning models can diagnose diseases from medical images with accuracy rivaling expert physicians. Financial institutions use AI for fraud detection, analyzing millions of transactions in real-time to identify suspicious patterns. Autonomous vehicles rely on computer vision and sensor fusion to navigate complex environments safely. Manufacturing plants employ AI-powered robots that can adapt to changing conditions and optimize production processes.

However, the rise of AI also presents significant challenges. Questions about bias in machine learning models have sparked important discussions about fairness and accountability. When training data reflects societal prejudices, AI systems can perpetuate and amplify these biases. Privacy concerns arise as organizations collect vast amounts of personal data to train their models. The potential displacement of workers by automation raises economic and social questions that society must address.

Climate Change and Environmental Sustainability

Climate change represents one of the most pressing challenges facing humanity. Rising global temperatures are causing widespread environmental disruptions. Polar ice caps are melting at unprecedented rates, contributing to sea level rise that threatens coastal communities worldwide. Extreme weather events, including hurricanes, droughts, and wildfires, are becoming more frequent and severe.

The primary driver of climate change is the accumulation of greenhouse gases in the atmosphere, particularly carbon dioxide from fossil fuel combustion. Industrial processes, transportation, and electricity generation contribute significantly to these emissions. Deforestation exacerbates the problem by reducing the planet's capacity to absorb carbon dioxide. The concentration of atmospheric CO2 has increased by over 40% since pre-industrial times.

Addressing climate change requires coordinated global action. Renewable energy technologies, such as solar and wind power, offer pathways to reduce carbon emissions. Energy efficiency improvements in buildings and transportation can significantly decrease energy consumption. Carbon capture and storage technologies aim to remove CO2 from the atmosphere or prevent its release. International agreements like the Paris Climate Accord establish frameworks for countries to commit to emission reduction targets.

Individual actions also play a crucial role in combating climate change. Reducing meat consumption, especially beef, can lower one's carbon footprint substantially. Using public transportation, cycling, or walking instead of driving reduces emissions. Energy-conscious choices in daily life, such as using LED bulbs and efficient appliances, contribute to overall energy conservation. Supporting businesses and policies that prioritize sustainability helps drive systemic change.

Scientific Discoveries and Innovation

Scientific research continues to unlock mysteries of the universe and develop groundbreaking technologies. The recent detection of gravitational waves confirmed Einstein's century-old predictions and opened a new window for observing cosmic phenomena. CRISPR gene-editing technology has revolutionized biology, enabling precise modifications to DNA with potential applications in treating genetic diseases. Quantum computing promises to solve problems that are intractable for classical computers, with implications for cryptography, drug discovery, and materials science.

Advances in neuroscience are revealing the complexities of the human brain. Brain-computer interfaces allow paralyzed individuals to control prosthetic limbs or communicate through thought alone. Understanding neural plasticity has led to new approaches for treating neurological conditions and enhancing cognitive function. Mapping the brain's connectome provides insights into how neural networks give rise to consciousness and behavior.

Space exploration has entered an exciting new era. Private companies are developing reusable rockets that dramatically reduce the cost of space access. Missions to Mars are preparing for eventual human colonization of the Red Planet. The James Webb Space Telescope is capturing unprecedented images of distant galaxies, helping astronomers understand the early universe. Exoplanet discoveries have revealed thousands of worlds beyond our solar system, raising profound questions about the existence of extraterrestrial life.

The intersection of different scientific disciplines is driving innovation. Bioinformatics combines biology and computer science to analyze genomic data. Nanotechnology manipulates matter at the atomic scale to create new materials with remarkable properties. Synthetic biology engineers organisms to produce valuable compounds, from pharmaceuticals to biofuels. These interdisciplinary approaches are accelerating the pace of discovery and creating solutions to complex problems.

Medical Advances and Clinical Applications

Modern clinical practice has been revolutionized by advances in medical imaging and diagnostics. Magnetic resonance imaging (MRI) and computed tomography (CT) scanning provide detailed anatomical information enabling early disease detection. Positron emission tomography (PET) combined with CT allows oncologists to identify metastatic lesions and assess treatment response in cancer patients. Electrocardiography (ECG) and echocardiography remain essential tools for evaluating cardiac pathology and ventricular function in patients presenting with arrhythmias or heart failure.

Pharmaceutical innovation continues to expand therapeutic options for previously intractable conditions. Monoclonal antibodies targeting specific antigens have transformed treatment protocols for rheumatoid arthritis, inflammatory bowel disease, and various malignancies. Tyrosine kinase inhibitors demonstrate remarkable efficacy in chronic myeloid leukemia and other oncologic conditions. Checkpoint inhibitors unleash the immune system's capacity to recognize and eliminate tumor cells, fundamentally changing approaches to immunotherapy. Biologics production through recombinant DNA technology has enabled the development of insulin analogs, growth hormones, and clotting factors that save countless lives annually.

Clinical laboratory science plays a critical role in diagnostic medicine. Complete blood count (CBC) analysis evaluates hematologic parameters including hemoglobin, hematocrit, and white blood cell differentials. Comprehensive metabolic panels assess renal function through creatinine and blood urea nitrogen measurements, hepatic function via bilirubin and transaminase levels, and glucose metabolism through fasting glucose and hemoglobin A1c determinations. Lipid panels quantifying cholesterol, triglycerides, and lipoprotein fractions guide cardiovascular risk stratification and therapeutic intervention.

Surgical innovation has enhanced patient outcomes through minimally invasive techniques. Laparoscopic cholecystectomy has largely replaced open approaches for gallbladder disease, reducing postoperative pain and hospitalization duration. Robot-assisted radical prostatectomy offers improved visualization and precision in oncologic urologic procedures. Endoscopic approaches to gastroesophageal reflux disease and bariatric surgery provide alternatives to traditional open surgery. Video-assisted thoracoscopic surgery (VATS) enables lung resection for both malignant and benign pathology with reduced morbidity compared to open thoracotomy.

Infectious Disease and Epidemiology

Infectious disease management requires understanding microbial pathogenesis and antimicrobial susceptibility. Bacterial infections are treated according to culture results and antibiotic sensitivities determined through disk diffusion or broth microdilution methods. Gram-positive cocci including Streptococcus pneumoniae and Staphylococcus aureus cause community-acquired pneumonia and must be distinguished from gram-negative organisms requiring different empiric therapy. Mycobacterial infections including tuberculosis demand prolonged treatment with isoniazid, rifampin, pyrazinamide, and ethambutol to prevent treatment failure and drug resistance.

Viral hepatitis encompasses distinct pathogens with varying transmission routes and clinical consequences. Hepatitis A causes acute inflammation but does not progress to chronicity. Hepatitis B and C virus infections establish chronic viremia, leading to progressive hepatic fibrosis, cirrhosis, and hepatocellular carcinoma in untreated patients. Direct-acting antiviral agents achieve cure rates exceeding 95 percent in hepatitis C genotypes, revolutionizing prognosis for millions of chronically infected patients. Hepatitis B treatment with nucleos(t)ide reverse transcriptase inhibitors suppresses viral replication, preventing disease progression to decompensated cirrhosis.

HIV infection remains a significant public health challenge despite effective antiretroviral therapy. Combination antiretroviral regimens utilizing nucleoside reverse transcriptase inhibitors, non-nucleoside reverse transcriptase inhibitors, protease inhibitors, and integrase inhibitors suppress viral replication to undetectable levels. CD4 cell count recovery following immune reconstitution allows discontinuation of opportunistic infection prophylaxis. Virologic failure with emergence of drug-resistant variants necessitates therapeutic drug monitoring and genotypic resistance testing to guide salvage regimens.

Chronic Disease Management and Epidemiology

Type 2 diabetes mellitus represents a pandemic affecting over 400 million individuals globally. Pathophysiology involves insulin resistance at the cellular level combined with progressive beta cell dysfunction. Management strategies include lifestyle modification, oral hypoglycemic agents including metformin, sulfonylureas, thiazolidinediones, and newer agents such as glucagon-like peptide-1 receptor agonists and sodium-glucose cotransporter-2 inhibitors. Tight glycemic control targeting hemoglobin A1c below 7 percent reduces microvascular complications including diabetic retinopathy, nephropathy, and neuropathy.

Hypertension affects approximately 1.1 billion individuals worldwide and represents the leading modifiable risk factor for cardiovascular morbidity and mortality. Pathophysiology involves abnormal vascular tone regulation, fluid retention, and sympathetic nervous system hyperactivity. Pharmacologic management utilizes angiotensin-converting enzyme inhibitors, angiotensin II receptor blockers, calcium channel blockers, thiazide and loop diuretics, and beta-adrenergic antagonists. Blood pressure targets vary by comorbidities, with most guidelines recommending systolic pressure below 130 mmHg to prevent stroke and myocardial infarction.

Heart failure affects over 26 million individuals globally and represents a major cause of hospitalization in developed nations. Systolic heart failure results from reduced ejection fraction due to myocardial infarction, cardiomyopathy, or chronic hypertension. Diastolic heart failure involves normal ejection fraction with impaired ventricular relaxation. Management incorporates beta-blockers, ACE inhibitors, aldosterone antagonists, and newer agents including ARNI complexes. Implantable cardioverter-defibrillators and cardiac resynchronization therapy benefit appropriate candidates with reduced ejection fraction.

Oncology and Cancer Treatment

Malignant neoplasms represent the second leading cause of death globally after cardiovascular disease. Carcinogenesis involves accumulation of genetic mutations in proto-oncogenes and tumor suppressor genes including p53 and RB. Pathologic staging using TNM classification determines prognosis and guides therapeutic recommendations. Screening programs for breast, colorectal, and cervical cancers have reduced mortality through early detection of precancerous lesions and stage I disease.

Chemotherapy regimens utilize cytotoxic agents targeting rapidly dividing cells. Alkylating agents damage DNA through formation of covalent bonds. Platinum compounds including cisplatin and carboplatin create interstrand DNA crosslinks preventing replication. Antimetabolites including methotrexate inhibit nucleotide synthesis disrupting DNA and RNA synthesis. Topoisomerase inhibitors prevent DNA unwinding necessary for replication and transcription. Systemic toxicity including myelosuppression, mucositis, and nephrotoxicity necessitates supportive care and dose modification in susceptible patients.

Radiation oncology utilizes ionizing radiation to destroy malignant cells. External beam radiotherapy delivers photons or particles through linear accelerators with precise spatial targeting. Intensity-modulated radiation therapy (IMRT) shapes radiation fields to conform to tumor contours while minimizing dose to adjacent normal tissues. Brachytherapy delivers radioactive sources directly into tumors enabling high local doses with rapid dose falloff. Complications including dermatitis, esophagitis, and secondary malignancies require careful risk-benefit analysis during treatment planning.

The Future of Work and Education

The nature of work is evolving rapidly in response to technological advancement. Remote work has become mainstream, enabled by video conferencing, cloud computing, and collaborative software. This shift challenges traditional notions of the workplace and opens opportunities for global talent collaboration. However, it also raises questions about work-life balance, social isolation, and the need for physical office spaces.

Automation and AI are transforming job markets across sectors. Routine tasks in manufacturing, data entry, and customer service are increasingly performed by machines. This trend creates demand for new skills focused on creativity, critical thinking, and human interaction. Workers must engage in continuous learning to remain relevant in evolving industries. Reskilling and upskilling programs help people transition to new careers as job requirements change.

Education systems are adapting to prepare students for this dynamic landscape. Online learning platforms provide access to educational resources for millions of people worldwide. Personalized learning powered by AI can adapt to individual student needs and learning styles. Project-based learning emphasizes practical skills and problem-solving abilities. STEM education receives increased focus to meet demand for technical expertise in emerging fields.

The gig economy represents a significant shift in employment relationships. Freelancing and contract work offer flexibility but often lack the security and benefits of traditional employment. Platform-based work through services like ride-sharing and delivery apps provides income opportunities but raises concerns about worker protections and fair compensation. Policymakers grapple with updating labor laws to address these new forms of work.

Global Health and Pandemics

The COVID-19 pandemic highlighted the importance of global health infrastructure and rapid scientific response. Vaccines were developed at unprecedented speed, showcasing the power of international collaboration and biotechnology. The pandemic also exposed disparities in healthcare access and the need for resilient supply chains. Telemedicine became a vital tool, enabling remote consultations and reducing the burden on hospitals. Lessons learned from COVID-19 are shaping preparedness for future pandemics, emphasizing surveillance, early detection, and equitable distribution of medical resources.

Arts, Culture, and Society

Art and culture continue to evolve alongside technology. Digital art forms, such as NFTs and virtual reality exhibitions, are redefining how people create and experience art. Streaming platforms have transformed music, film, and television distribution, making content accessible to global audiences. Social media influences trends, public opinion, and even political movements. At the same time, there is renewed interest in preserving cultural heritage and supporting local artists. The intersection of technology and culture raises questions about authenticity, ownership, and the impact of algorithms on creative expression.

Sports and Human Performance

Advancements in sports science and technology are pushing the boundaries of human performance. Wearable devices track athletes' biometrics, optimizing training and recovery. Data analytics inform coaching strategies and player selection. Innovations in equipment design, such as carbon fiber running shoes and aerodynamic bicycles, contribute to record-breaking achievements. The integration of mental health support and mindfulness practices is recognized as essential for athlete well-being. Major sporting events foster international unity and inspire the next generation of competitors.

Economics and Globalization

The global economy is increasingly interconnected. Supply chain disruptions, trade agreements, and geopolitical tensions influence markets worldwide. Cryptocurrencies and blockchain technology are challenging traditional financial systems, offering new opportunities and risks. Economic inequality remains a pressing issue, with debates about universal basic income, wealth taxes, and social safety nets. Sustainable development goals guide efforts to balance economic growth with environmental protection and social equity.

Conclusion and Looking Forward

As we navigate these transformative times, the interconnection between technological progress, environmental stewardship, scientific discovery, and societal evolution becomes increasingly apparent. The choices we make today will shape the world for future generations. Balancing innovation with ethical considerations, economic growth with environmental sustainability, and individual freedom with collective responsibility requires thoughtful deliberation and collaborative action.

Success in addressing global challenges depends on international cooperation, informed decision-making, and the willingness to adapt long-held assumptions. Education, critical thinking, and open dialogue are essential for navigating complexity and uncertainty. By embracing both the opportunities and responsibilities that come with advancement, humanity can work toward a future that is prosperous, sustainable, and equitable for all.
"""
print(f"📝 Sample text length: {len(sample_text)} characters")
print(f"📊 Approximate word count: {len(sample_text.split())} words")
print("✅ Sample text ready for chunking!")

📝 Sample text length: 18999 characters
📊 Approximate word count: 2347 words
✅ Sample text ready for chunking!


---

# 🔤 Understanding Tokenizers in Chonkie

Before diving into chunking strategies, let's explore the different **tokenizers** available in Chonkie. Tokenizers determine how text is split into tokens, which affects chunk sizes and boundaries.

## 📋 Tokenizer Types

Chonkie supports multiple tokenizer types:

1. **Built-in Tokenizers**:
   - `"character"` - Character-level tokenization (1 character = 1 token)
   - `"word"` - Word-level tokenization (splits on whitespace)
   - `"gpt2"` - GPT-2 BPE tokenizer (OpenAI's tokenization)

2. **Hugging Face Tokenizers**:
   - Any tokenizer from the Hugging Face Hub
   - Examples: `"bert-base-uncased"`, `"roberta-base"`, `"t5-small"`, etc.

The tokenizer choice impacts:
- **Chunk size precision**: Character vs. subword vs. word granularity
- **Compatibility**: Match your downstream model's tokenizer
- **Language support**: Some tokenizers handle multilingual text better

In [7]:
## Chonkie Built-in Tokenizers

chonkie_tokenizers = [
    "character",  # Character-level: Each character = 1 token
    "word",       # Word-level: Splits on whitespace
    "gpt2"        # GPT-2 BPE tokenizer (default for many models)
]

print("🔤 Chonkie Built-in Tokenizers:")
print("=" * 60)
for idx, tokenizer in enumerate(chonkie_tokenizers, 1):
    descriptions = {
        "character": "Character-level (fastest, most granular)",
        "word": "Word-level (simple, whitespace-based)",
        "gpt2": "GPT-2 BPE (standard for GPT models)"
    }
    print(f"{idx}. {tokenizer:15s} - {descriptions[tokenizer]}")

print("\n✅ These tokenizers are ready to use without additional downloads!")
print("   Example: TokenChunker(tokenizer='gpt2', chunk_size=512)")

🔤 Chonkie Built-in Tokenizers:
1. character       - Character-level (fastest, most granular)
2. word            - Word-level (simple, whitespace-based)
3. gpt2            - GPT-2 BPE (standard for GPT models)

✅ These tokenizers are ready to use without additional downloads!
   Example: TokenChunker(tokenizer='gpt2', chunk_size=512)


In [15]:
## Popular Hugging Face Tokenizers

# Select popular HuggingFace tokenizers that are compatible with Chonkie
popular_hf_tokenizers = [
    "bert-base-uncased",      # BERT - Great for general text
    "roberta-base",           # RoBERTa - Improved BERT variant
    "distilbert-base-uncased", # DistilBERT - Faster, lighter BERT
    "albert-base-v2",         # ALBERT - Parameter-efficient BERT variant
    "answerdotai/ModernBERT-base",  # ModernBERT - State-of-the-art 2024 model
    "sentence-transformers/all-MiniLM-L6-v2",  # Optimized for embeddings
    "llama-tokenizer",        # LlamaTokenizer - Llama models, large context
    "t5-base",                # T5Tokenizer - Text-to-text transformer
    "xlnet-base-cased"        # XLNetTokenizer - Permutation-based language model
]

descriptions = {
    "bert-base-uncased": "BERT - WordPiece tokenization, 30K vocab",
    "roberta-base": "RoBERTa - BPE tokenization, 50K vocab",
    "distilbert-base-uncased": "DistilBERT - Lighter BERT, 30K vocab",
    "albert-base-v2": "ALBERT - Efficient BERT, shared parameters",
    "answerdotai/ModernBERT-base": "ModernBERT - Latest architecture, 8K context",
    "sentence-transformers/all-MiniLM-L6-v2": "MiniLM - Optimized for sentence embeddings",
    "llama-tokenizer": "LlamaTokenizer - Llama models, large context windows",
    "t5-base": "T5Tokenizer - Text-to-text transformer, 32K vocab",
    "xlnet-base-cased": "XLNetTokenizer - Permutation-based, 32K vocab"
}

print("🤗 Popular Hugging Face Tokenizers:")
print("=" * 60)
for idx, tokenizer in enumerate(popular_hf_tokenizers, 1):
    print(f"{idx}. {tokenizer}")
    print(f"   → {descriptions[tokenizer]}")

print("\n💡 Note: HuggingFace tokenizers will be auto-downloaded on first use")
print("   They provide more sophisticated tokenization than simple word/character splitting")
print("\n⚠️  Some tokenizers may have compatibility issues with Chonkie.")
print("   If you encounter errors, try using a different tokenizer from the list.")

🤗 Popular Hugging Face Tokenizers:
1. bert-base-uncased
   → BERT - WordPiece tokenization, 30K vocab
2. roberta-base
   → RoBERTa - BPE tokenization, 50K vocab
3. distilbert-base-uncased
   → DistilBERT - Lighter BERT, 30K vocab
4. albert-base-v2
   → ALBERT - Efficient BERT, shared parameters
5. answerdotai/ModernBERT-base
   → ModernBERT - Latest architecture, 8K context
6. sentence-transformers/all-MiniLM-L6-v2
   → MiniLM - Optimized for sentence embeddings
7. llama-tokenizer
   → LlamaTokenizer - Llama models, large context windows
8. t5-base
   → T5Tokenizer - Text-to-text transformer, 32K vocab
9. xlnet-base-cased
   → XLNetTokenizer - Permutation-based, 32K vocab

💡 Note: HuggingFace tokenizers will be auto-downloaded on first use
   They provide more sophisticated tokenization than simple word/character splitting

⚠️  Some tokenizers may have compatibility issues with Chonkie.
   If you encounter errors, try using a different tokenizer from the list.


---

# 🔢 1. TokenChunker: Fixed-Size Token-Based Chunking

## Overview
The **TokenChunker** splits text into chunks based on a fixed number of tokens. This is the most straightforward chunking method and is ideal when you need consistent chunk sizes for token-based models like GPT.

### Key Features:
- ✅ Fixed token count per chunk
- ✅ Configurable overlap between chunks
- ✅ Works with various tokenizers (GPT-2, TikToken, etc.)
- ✅ Best for maintaining consistent chunk sizes

### Use Cases:
- Token-limited API calls
- Consistent embedding dimensions
- Simple text segmentation

In [16]:
# Combine all available tokenizers for dropdown
all_tokenizers = chonkie_tokenizers + popular_hf_tokenizers

# Interactive TokenChunker with parameter controls including tokenizer selection
@interact(
    tokenizer=widgets.Dropdown(
        options=all_tokenizers,
        value="gpt2",
        description='Tokenizer:',
        style={'description_width': 'initial'}
    ),
    chunk_size=widgets.IntSlider(min=64, max=1024, step=64, value=512, description='Chunk Size'),
    chunk_overlap=widgets.IntSlider(min=0, max=200, step=10, value=50, description='Overlap')
)
def visualize_token_chunker(tokenizer="gpt2", chunk_size=512, chunk_overlap=50):
    print(f"🔄 Using tokenizer: {tokenizer}")
    
    # Initialize TokenChunker
    token_chunker = TokenChunker(
        tokenizer=tokenizer,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )
    
    # Chunk the sample text
    token_chunks = token_chunker.chunk(sample_text)

    
    # Visualize with colors
    viz = Visualizer()
    print("\n\n🎨 HTML Visualization with Color-Coded Chunks:")
    viz.save("token_chunks_viz.html", token_chunks)
    with open("token_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
    display(HTML(html_content))

        # Display statistics
    print("📊 TokenChunker Results:")
    print(f"Total chunks created: {len(token_chunks)}")
    print(f"\nFirst 3 chunks details:")
    for i, chunk in enumerate(token_chunks[:3]):
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Character count: {len(chunk.text)}")
        print(f"  Preview: {chunk.text[:100]}...")
        
        # Show overlap with previous chunk
        if i > 0 and chunk_overlap > 0:
            prev_chunk = token_chunks[i-1]
            # Find overlapping text (approximate by comparing end of prev with start of current)
            overlap_text = ""
            for length in range(min(len(prev_chunk.text), len(chunk.text)), 0, -1):
                if prev_chunk.text[-length:] == chunk.text[:length]:
                    overlap_text = chunk.text[:length]
                    break
            if overlap_text:
                print(f"  🔄 Overlap with Chunk {i}: {len(overlap_text)} chars")
                print(f"     → \"{overlap_text[:80]}...\"")

interactive(children=(Dropdown(description='Tokenizer:', index=2, options=('character', 'word', 'gpt2', 'bert-…

### 🎨 Understanding the Color Visualization

In all HTML visualizations below, Chonkie's Visualizer displays chunks with the following color scheme:

| Visual Element | Meaning |
|----------------|---------|
| **🎨 Colored Backgrounds** | Each chunk gets a **unique background color** from a rotating palette |
| **📊 Chunk Boundaries** | Where one background color ends and another begins = chunk boundary |
| **🔄 Overlap Regions** | Text in overlapping regions appears in **both adjacent chunks** with their respective colors |
| **🌈 Color Cycling** | Colors rotate through a palette (blue, purple, pink, green, yellow, cyan, etc.) |

#### Understanding Overlap (when `chunk_overlap` > 0):

```
Example with overlap=50 tokens:
┌─────────────────────────────┐
│  Chunk 1 (Blue Background)  │───┐
│  "...end of chunk 1 text"   │   │← Overlap: These 50 tokens
└─────────────────────────────┘   │   appear in BOTH chunks
     ┌────────────────────────────┘
     │  "...end of chunk 1 text"      │
     │  Chunk 2 (Purple Background)   │
     │  "beginning of chunk 2..."     │
     └────────────────────────────────┘
```

**💡 Key Insight**: Overlapping text will appear twice in the visualization - once with Chunk 1's color and again with Chunk 2's color. This ensures continuity and context preservation across chunk boundaries!

---

# 📄 2. SentenceChunker: Sentence Boundary-Preserving Chunks

## Overview
The **SentenceChunker** splits text while preserving complete sentences. Unlike TokenChunker which can split mid-sentence, this chunker ensures that each chunk contains only complete sentences, maintaining semantic coherence.

### Key Features:
- ✅ Preserves sentence boundaries
- ✅ Maintains semantic completeness
- ✅ Configurable minimum sentences per chunk
- ✅ Respects natural language structure

### Use Cases:
- Question-answering systems
- Semantic search applications
- When context preservation is critical

In [ ]:
# Interactive SentenceChunker with parameter controls
@interact(
    tokenizer=widgets.Dropdown(
        options=all_tokenizers,
        value="gpt2",
        description='Tokenizer:',
        style={'description_width': 'initial'}
    ),
    chunk_size=widgets.IntSlider(min=128, max=1024, step=64, value=512, description='Chunk Size'),
    chunk_overlap=widgets.IntSlider(min=0, max=200, step=10, value=50, description='Overlap'),
    min_sentences=widgets.IntSlider(min=1, max=5, step=1, value=2, description='Min Sentences')
)
def visualize_sentence_chunker(tokenizer="gpt2", chunk_size=512, chunk_overlap=50, min_sentences=2):
    print(f"🔄 Using tokenizer: {tokenizer}")
    
    # Initialize SentenceChunker
    sentence_chunker = SentenceChunker(
        tokenizer=tokenizer,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        min_sentences_per_chunk=min_sentences,
        min_characters_per_sentence=12
    )
    
    # Chunk the sample text
    sentence_chunks = sentence_chunker.chunk(sample_text)
    
    # Visualize with colors
    viz = Visualizer()
    print("\n\n🎨 HTML Visualization with Color-Coded Chunks:")
    viz.save("sentence_chunks_viz.html", sentence_chunks)
    with open("sentence_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
    display(HTML(html_content))

    # Display statistics
    print("📊 SentenceChunker Results:")
    print(f"Total chunks created: {len(sentence_chunks)}")
    print(f"\nFirst 3 chunks details:")
    for i, chunk in enumerate(sentence_chunks[:3]):
        sentences_count = chunk.text.count('.') + chunk.text.count('!') + chunk.text.count('?')
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Approximate sentences: {sentences_count}")
        print(f"  Preview: {chunk.text[:120]}...")
        
        # Show overlap with previous chunk
        if i > 0 and chunk_overlap > 0:
            prev_chunk = sentence_chunks[i-1]
            overlap_text = ""
            for length in range(min(len(prev_chunk.text), len(chunk.text)), 0, -1):
                if prev_chunk.text[-length:] == chunk.text[:length]:
                    overlap_text = chunk.text[:length]
                    break
            if overlap_text:
                print(f"  🔄 Overlap with Chunk {i}: {len(overlap_text)} chars")
                print(f"     → \"{overlap_text[:80]}...\"")

interactive(children=(Dropdown(description='Tokenizer:', index=2, options=('character', 'word', 'gpt2', 'bert-…

---

# 🔄 3. RecursiveChunker: Hierarchical Recursive Splitting

## Overview
The **RecursiveChunker** uses a hierarchical approach, recursively splitting text using different delimiters (paragraphs, sentences, words, characters). It tries to split at the largest possible delimiter first, then recursively uses smaller delimiters if needed.

### Key Features:
- ✅ Multi-level delimiter hierarchy
- ✅ Preserves document structure
- ✅ Intelligent fallback mechanism
- ✅ Customizable splitting rules

### Use Cases:
- Structured documents (books, articles)
- Markdown or formatted text
- When preserving hierarchical structure matters

In [ ]:
# Interactive RecursiveChunker with parameter controls
@interact(
    tokenizer=widgets.Dropdown(
        options=all_tokenizers,
        value="gpt2",
        description='Tokenizer:',
        style={'description_width': 'initial'}
    ),
    chunk_size=widgets.IntSlider(min=128, max=1024, step=64, value=512, description='Chunk Size'),
    min_chars=widgets.IntSlider(min=12, max=100, step=4, value=24, description='Min Chars')
)
def visualize_recursive_chunker(tokenizer="gpt2", chunk_size=512, min_chars=24):
    print(f"🔄 Using tokenizer: {tokenizer}")
    
    # Initialize RecursiveChunker
    recursive_chunker = RecursiveChunker(
        tokenizer=tokenizer,
        chunk_size=chunk_size,
        min_characters_per_chunk=min_chars
    )
    
    # Chunk the sample text
    recursive_chunks = recursive_chunker.chunk(sample_text)
    
    # Visualize with colors
    viz = Visualizer()
    print("\n\n🎨 HTML Visualization with Color-Coded Chunks:")
    viz.save("recursive_chunks_viz.html", recursive_chunks)
    with open("recursive_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
    display(HTML(html_content))

    # Display statistics
    print("📊 RecursiveChunker Results:")
    print(f"Total chunks created: {len(recursive_chunks)}")
    print(f"\nFirst 3 chunks details:")
    for i, chunk in enumerate(recursive_chunks[:3]):
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Character count: {len(chunk.text)}")
        print(f"  Start index: {chunk.start_index}")
        print(f"  Preview: {chunk.text[:120]}...")
        
        # Show overlap with previous chunk if any exists
        if i > 0:
            prev_chunk = recursive_chunks[i-1]
            overlap_text = ""
            for length in range(min(len(prev_chunk.text), len(chunk.text)), 0, -1):
                if prev_chunk.text[-length:] == chunk.text[:length]:
                    overlap_text = chunk.text[:length]
                    break
            if overlap_text:
                print(f"  🔄 Overlap with Chunk {i}: {len(overlap_text)} chars")
                print(f"     → \"{overlap_text[:80]}...\"")
    

interactive(children=(Dropdown(description='Tokenizer:', index=2, options=('character', 'word', 'gpt2', 'bert-…

---

# 🧠 4. SemanticChunker: Similarity-Based Semantic Grouping

## Overview
The **SemanticChunker** is one of the most advanced chunking strategies. It analyzes the semantic similarity between sentences and groups together content that is semantically related. This ensures that chunks contain topically coherent information.

### Key Features:
- ✅ Groups semantically similar content
- ✅ Uses embeddings to measure similarity
- ✅ Savitzky-Golay filtering for smooth boundaries
- ✅ Optional skip-window merging for non-consecutive similar groups
- ✅ Preserves topical coherence

### How It Works:
1. Splits text into sentences
2. Generates embeddings for each sentence
3. Calculates similarity between sentences
4. Groups sentences with similarity above threshold
5. Applies filtering for smoother boundaries

### Use Cases:
- Topic-based retrieval systems
- When semantic coherence is paramount
- Multi-topic documents
- RAG applications requiring context preservation

In [36]:
## Embedding Models for Semantic Chunking

# Popular embedding models optimized for semantic similarity tasks
semantic_embedding_models = [
    "minishlab/potion-base-32M",           # Model2Vec - Ultra-fast, 32M params
    "sentence-transformers/all-MiniLM-L6-v2",  # Popular, balanced performance
    "sentence-transformers/all-mpnet-base-v2",  # High quality, general purpose
    "BAAI/bge-small-en-v1.5",               # BGE - Efficient, strong performance
    "BAAI/bge-base-en-v1.5",                # BGE - Better quality, slower
    "BAAI/bge-large-en-v1.5",               # BGE Large - Highest quality BGE
    "thenlper/gte-small",                   # GTE - General text embeddings
    "jinaai/jina-embeddings-v2-base-en",    # Jina v2 - 8K context, strong performance
    "nomic-ai/nomic-embed-text-v1.5",       # Nomic - Long context (8K tokens)
    "emilyalsentzer/Bio_ClinicalBERT",      # MedEmbed - Medical/clinical domain
    "kamalkraj/biobert-base-cased-v1.2",    # ClinVec - Biomedical text embeddings
    "google/gecko-text-embedding",          # Google Gecko - Multimodal embeddings
    "Alibaba-NLP/gte-large-en-v1.5",        # GTE Large - State-of-the-art, 1024 dims
    "Alibaba-NLP/gte-Qwen2-7B-instruct",    # GTE Qwen2 - Instruction-tuned, 7B params
]

print("🧠 Embedding Models for SemanticChunker:")
print("=" * 70)
for idx, model in enumerate(semantic_embedding_models, 1):
    model_descriptions = {
        "minishlab/potion-base-32M": "Model2Vec - Ultra-fast, lightweight (32M params)",
        "sentence-transformers/all-MiniLM-L6-v2": "MiniLM - Popular, balanced speed/quality",
        "sentence-transformers/all-mpnet-base-v2": "MPNet - High quality semantic search",
        "BAAI/bge-small-en-v1.5": "BGE Small - Efficient, strong performance",
        "BAAI/bge-base-en-v1.5": "BGE Base - Better quality, more compute",
        "BAAI/bge-large-en-v1.5": "BGE Large - Top-tier quality, 1024 dimensions",
        "thenlper/gte-small": "GTE - General text embeddings",
        "jinaai/jina-embeddings-v2-base-en": "Jina v2 - 8K context, bilingual support",
        "nomic-ai/nomic-embed-text-v1.5": "Nomic - Long context support (8K tokens)",
        "emilyalsentzer/Bio_ClinicalBERT": "MedEmbed - Specialized for medical/clinical text",
        "kamalkraj/biobert-base-cased-v1.2": "ClinVec - BioBERT for biomedical literature",
        "google/gecko-text-embedding": "Google Gecko - Multimodal, high quality",
        "Alibaba-NLP/gte-large-en-v1.5": "GTE Large - State-of-the-art, 1024 dimensions",
        "Alibaba-NLP/gte-Qwen2-7B-instruct": "GTE Qwen2 - Instruction-tuned, 7B params",
    }
    print(f"{idx}. {model}")
    print(f"   → {model_descriptions[model]}")

print("   • Best quality: all-mpnet-base-v2, BAAI/bge-large-en-v1.5, Alibaba-NLP/gte-large-en-v1.5")
print("   • Faster models: minishlab/potion-base-32M, thenlper/gte-small")
print("   • Large-scale: Alibaba-NLP/gte-Qwen2-7B-instruct (7B params, instruction-tuned)")
print("   • Default recommended: minishlab/potion-base-32M (fast + good quality)")
print("   • Medical/Clinical: emilyalsentzer/Bio_ClinicalBERT, kamalkraj/biobert-base-cased-v1.2")

🧠 Embedding Models for SemanticChunker:
1. minishlab/potion-base-32M
   → Model2Vec - Ultra-fast, lightweight (32M params)
2. sentence-transformers/all-MiniLM-L6-v2
   → MiniLM - Popular, balanced speed/quality
3. sentence-transformers/all-mpnet-base-v2
   → MPNet - High quality semantic search
4. BAAI/bge-small-en-v1.5
   → BGE Small - Efficient, strong performance
5. BAAI/bge-base-en-v1.5
   → BGE Base - Better quality, more compute
6. BAAI/bge-large-en-v1.5
   → BGE Large - Top-tier quality, 1024 dimensions
7. thenlper/gte-small
   → GTE - General text embeddings
8. jinaai/jina-embeddings-v2-base-en
   → Jina v2 - 8K context, bilingual support
9. nomic-ai/nomic-embed-text-v1.5
   → Nomic - Long context support (8K tokens)
10. emilyalsentzer/Bio_ClinicalBERT
   → MedEmbed - Specialized for medical/clinical text
11. kamalkraj/biobert-base-cased-v1.2
   → ClinVec - BioBERT for biomedical literature
12. google/gecko-text-embedding
   → Google Gecko - Multimodal, high quality
13. Alibaba

In [ ]:
# Interactive SemanticChunker with parameter controls
@interact(
    embedding_model=widgets.Dropdown(
        options=semantic_embedding_models,
        value="minishlab/potion-base-32M",
        description='Embedding:',
        style={'description_width': 'initial'}
    ),
    threshold=widgets.FloatSlider(min=0.3, max=0.95, step=0.05, value=0.7, description='Threshold'),
    chunk_size=widgets.IntSlider(min=128, max=1024, step=64, value=512, description='Chunk Size'),
    similarity_window=widgets.IntSlider(min=1, max=5, step=1, value=3, description='Sim Window'),
    skip_window=widgets.IntSlider(min=0, max=3, step=1, value=0, description='Skip Window')
)
def visualize_semantic_chunker(embedding_model="minishlab/potion-base-32M", threshold=0.7, chunk_size=512, similarity_window=3, skip_window=0):
    print(f"🔄 Using embedding model: {embedding_model}")
    print("🔄 Chunking with SemanticChunker (this may take a moment)...")
    
    # Initialize SemanticChunker
    semantic_chunker = SemanticChunker(
        embedding_model=embedding_model,
        threshold=threshold,
        chunk_size=chunk_size,
        similarity_window=similarity_window,
        skip_window=skip_window,
        min_sentences_per_chunk=1
    )
    
    # Chunk the sample text
    semantic_chunks = semantic_chunker.chunk(sample_text)
    
    
    # Visualize with colors
    print("\n\n🎨 HTML Visualization with Color-Coded Chunks:")
    print("Notice how semantically similar content is grouped together!")
    viz = Visualizer()
    viz.save("semantic_chunks_viz.html", semantic_chunks)
    with open("semantic_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
        display(HTML(html_content))

        # Display statistics
    print("\n📊 SemanticChunker Results:")
    print(f"Total chunks created: {len(semantic_chunks)}")
    print(f"\nFirst 3 chunks details:")
    for i, chunk in enumerate(semantic_chunks[:3]):
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Character count: {len(chunk.text)}")
        print(f"  Preview: {chunk.text[:150]}...")

interactive(children=(Dropdown(description='Embedding:', options=('minishlab/potion-base-32M', 'sentence-trans…

---

# ⚡ 5. LateChunker: Document-Level Contextual Embeddings

## Overview
The **LateChunker** implements the "Late Chunking" algorithm from the [research paper](https://arxiv.org/abs/2409.04701). Unlike traditional methods that embed each chunk independently, LateChunker first generates a document-level embedding and then derives chunk embeddings from it. This provides richer contextual information.

### Key Features:
- ✅ Document-level context preservation
- ✅ Embeddings capture broader context
- ✅ Built on RecursiveChunker base
- ✅ Better retrieval performance in RAG systems
- ✅ Each chunk includes its embedding

### How It Works:
1. Encodes entire document into single embedding
2. Splits text using recursive rules
3. Derives chunk embeddings from document embedding
4. Each chunk carries broader contextual information

### Use Cases:
- Advanced RAG applications
- When document-level context is important
- Improved retrieval accuracy
- Semantic search with rich context

In [39]:
# Interactive LateChunker with parameter controls
@interact(
    embedding_model=widgets.Dropdown(
        options=semantic_embedding_models,
        value="minishlab/potion-base-32M",
        description='Embedding:',
        style={'description_width': 'initial'}
    ),
    chunk_size=widgets.IntSlider(min=128, max=1024, step=64, value=512, description='Chunk Size'),
    min_chars=widgets.IntSlider(min=12, max=100, step=4, value=24, description='Min Chars')
)
def visualize_late_chunker(embedding_model="minishlab/potion-base-32M", chunk_size=512, min_chars=24):
    print(f"🔄 Using embedding model: {embedding_model}")
    print("🔄 Chunking with LateChunker (generating document-level embeddings)...")
    
    # Initialize LateChunker
    late_chunker = LateChunker(
        embedding_model=embedding_model,
        chunk_size=chunk_size,
        min_characters_per_chunk=min_chars
    )
    
    # Chunk the sample text
    late_chunks = late_chunker.chunk(sample_text)
    
    # Display statistics
    print("\n📊 LateChunker Results:")
    print(f"Total chunks created: {len(late_chunks)}")
    print(f"\nFirst 3 chunks details:")
    for i, chunk in enumerate(late_chunks[:3]):
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Character count: {len(chunk.text)}")
        if hasattr(chunk, 'embedding') and chunk.embedding is not None:
            print(f"  Embedding shape: {chunk.embedding.shape}")
        print(f"  Preview: {chunk.text[:150]}...")
    
    # Visualize with colors
    print("\n\n🎨 HTML Visualization with Color-Coded Chunks:")
    print("Each chunk contains embeddings derived from the full document context!")
    viz = Visualizer()
    viz.save("late_chunks_viz.html", late_chunks)
    with open("late_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
        display(HTML(html_content))

interactive(children=(Dropdown(description='Embedding:', options=('minishlab/potion-base-32M', 'sentence-trans…

---

# 💻 6. CodeChunker: AST-Based Code Structure Chunking

## Overview
The **CodeChunker** is specialized for source code. It uses Abstract Syntax Trees (AST) to understand code structure and creates chunks that respect programming language syntax. This is perfect for code documentation, code search, and AI-assisted coding.

### Key Features:
- ✅ AST-based parsing
- ✅ Respects code structure (functions, classes, etc.)
- ✅ Supports multiple programming languages
- ✅ Maintains syntactic validity
- ✅ Optional AST node information

### Supported Languages:
Python, JavaScript, TypeScript, Java, C++, Go, Rust, and many more via tree-sitter!

### Use Cases:
- Code documentation systems
- Code search engines
- AI code assistants
- Code analysis tools

In [40]:
# Sample Python code for demonstration
sample_code = """
import numpy as np
from typing import List, Dict, Optional

class DataProcessor:
    \"\"\"A class for processing and analyzing data.\"\"\"
    
    def __init__(self, data: List[float]):
        self.data = data
        self.processed = False
    
    def normalize(self) -> np.ndarray:
        \"\"\"Normalize the data using min-max scaling.\"\"\"
        data_array = np.array(self.data)
        min_val = np.min(data_array)
        max_val = np.max(data_array)
        normalized = (data_array - min_val) / (max_val - min_val)
        self.processed = True
        return normalized
    
    def calculate_statistics(self) -> Dict[str, float]:
        \"\"\"Calculate basic statistics of the data.\"\"\"
        data_array = np.array(self.data)
        stats = {
            'mean': np.mean(data_array),
            'median': np.median(data_array),
            'std': np.std(data_array),
            'min': np.min(data_array),
            'max': np.max(data_array)
        }
        return stats

def create_sample_data(size: int = 100) -> List[float]:
    \"\"\"Generate sample data for testing.\"\"\"
    return np.random.randn(size).tolist()

def main():
    \"\"\"Main function to demonstrate the DataProcessor.\"\"\"
    # Create sample data
    data = create_sample_data(50)
    
    # Initialize processor
    processor = DataProcessor(data)
    
    # Normalize and get statistics
    normalized = processor.normalize()
    stats = processor.calculate_statistics()
    
    print(f"Statistics: {stats}")
    print(f"First 5 normalized values: {normalized[:5]}")

if __name__ == "__main__":
    main()
"""

# Interactive CodeChunker with parameter controls
@interact(
    tokenizer=widgets.Dropdown(
        options=all_tokenizers,
        value="gpt2",
        description='Tokenizer:',
        style={'description_width': 'initial'}
    ),
    chunk_size=widgets.IntSlider(min=128, max=768, step=64, value=256, description='Chunk Size')
)
def visualize_code_chunker(tokenizer="gpt2", chunk_size=256):
    print(f"🔄 Chunking Python code with CodeChunker...")
    print(f"🔄 Using tokenizer: {tokenizer}")
    
    # Initialize CodeChunker for Python
    code_chunker = CodeChunker(
        language="python",
        tokenizer=tokenizer,
        chunk_size=chunk_size,
        include_nodes=False
    )
    
    # Chunk the code
    code_chunks = code_chunker.chunk(sample_code)
    
    # Display statistics
    print(f"\n📊 CodeChunker Results:")
    print(f"Total chunks created: {len(code_chunks)}")
    print(f"\nChunk details:")
    for i, chunk in enumerate(code_chunks):
        print(f"\n🔹 Chunk {i+1}:")
        print(f"  Token count: {chunk.token_count}")
        print(f"  Lines of code: {chunk.text.count(chr(10)) + 1}")
        print(f"  Preview:")
        print(f"  {chunk.text[:200]}...")
    
    # Visualize with colors
    print("\n\n🎨 HTML Visualization with Color-Coded Code Chunks:")
    print("Notice how chunks respect code structure (classes, functions, etc.)!")
    viz = Visualizer()
    viz.save("code_chunks_viz.html", code_chunks)
    with open("code_chunks_viz.html", "r", encoding="utf-8") as f:
        html_content = f.read()
        display(HTML(html_content))

interactive(children=(Dropdown(description='Tokenizer:', index=2, options=('character', 'word', 'gpt2', 'bert-…

---

# 📊 Comparison: How Different Chunkers Affect the Same Text

Let's compare how each chunker handles the same piece of text to understand their unique characteristics.

In [42]:
import pandas as pd

# Create chunks for comparison (using default parameters)
print("🔄 Creating chunks with default parameters for comparison...")

token_chunker = TokenChunker(tokenizer="gpt2", chunk_size=512, chunk_overlap=50)
token_chunks = token_chunker.chunk(sample_text)

sentence_chunker = SentenceChunker(tokenizer="gpt2", chunk_size=512, chunk_overlap=50, min_sentences_per_chunk=2)
sentence_chunks = sentence_chunker.chunk(sample_text)

recursive_chunker = RecursiveChunker(tokenizer="gpt2", chunk_size=512, min_characters_per_chunk=24)
recursive_chunks = recursive_chunker.chunk(sample_text)

semantic_chunker = SemanticChunker(embedding_model="minishlab/potion-base-32M", threshold=0.7, chunk_size=512)
semantic_chunks = semantic_chunker.chunk(sample_text)

late_chunker = LateChunker(embedding_model="minishlab/potion-base-32M", chunk_size=512, min_characters_per_chunk=24)
late_chunks = late_chunker.chunk(sample_text)

print("✅ All chunks created!\n")

# Create comparison data
comparison_data = {
    'Chunker': [
        'TokenChunker',
        'SentenceChunker', 
        'RecursiveChunker',
        'SemanticChunker',
        'LateChunker'
    ],
    'Total Chunks': [
        len(token_chunks),
        len(sentence_chunks),
        len(recursive_chunks),
        len(semantic_chunks),
        len(late_chunks)
    ],
    'Avg Tokens/Chunk': [
        sum(c.token_count for c in token_chunks) / len(token_chunks),
        sum(c.token_count for c in sentence_chunks) / len(sentence_chunks),
        sum(c.token_count for c in recursive_chunks) / len(recursive_chunks),
        sum(c.token_count for c in semantic_chunks) / len(semantic_chunks),
        sum(c.token_count for c in late_chunks) / len(late_chunks)
    ],
    'Key Characteristic': [
        'Fixed token boundaries',
        'Sentence boundaries',
        'Hierarchical delimiters',
        'Semantic similarity',
        'Document context'
    ]
}

df = pd.DataFrame(comparison_data)
df['Avg Tokens/Chunk'] = df['Avg Tokens/Chunk'].round(1)

print("📊 Chunking Strategy Comparison:")
print("=" * 80)
print(df.to_string(index=False))
print("=" * 80)

# Detailed breakdown
print("\n\n📈 Detailed Statistics:")
print("\n1️⃣ TokenChunker:")
print(f"   - Most consistent chunk sizes (target: 512 tokens)")
print(f"   - Min tokens: {min(c.token_count for c in token_chunks)}")
print(f"   - Max tokens: {max(c.token_count for c in token_chunks)}")

print("\n2️⃣ SentenceChunker:")
print(f"   - Preserves sentence boundaries")
print(f"   - Variable chunk sizes based on sentence length")
print(f"   - Min tokens: {min(c.token_count for c in sentence_chunks)}")
print(f"   - Max tokens: {max(c.token_count for c in sentence_chunks)}")

print("\n3️⃣ RecursiveChunker:")
print(f"   - Hierarchical splitting approach")
print(f"   - Respects paragraph and sentence structure")
print(f"   - Min tokens: {min(c.token_count for c in recursive_chunks)}")
print(f"   - Max tokens: {max(c.token_count for c in recursive_chunks)}")

print("\n4️⃣ SemanticChunker:")
print(f"   - Groups semantically similar content")
print(f"   - Variable sizes based on topic coherence")
print(f"   - Min tokens: {min(c.token_count for c in semantic_chunks)}")
print(f"   - Max tokens: {max(c.token_count for c in semantic_chunks)}")

print("\n5️⃣ LateChunker:")
print(f"   - Document-level contextual embeddings")
print(f"   - Similar to RecursiveChunker but with richer embeddings")
print(f"   - Min tokens: {min(c.token_count for c in late_chunks)}")
print(f"   - Max tokens: {max(c.token_count for c in late_chunks)}")

🔄 Creating chunks with default parameters for comparison...
✅ All chunks created!

📊 Chunking Strategy Comparison:
         Chunker  Total Chunks  Avg Tokens/Chunk      Key Characteristic
    TokenChunker             8             457.1  Fixed token boundaries
 SentenceChunker             8             446.8     Sentence boundaries
RecursiveChunker             8             413.4 Hierarchical delimiters
 SemanticChunker            52              56.0     Semantic similarity
     LateChunker             7               1.0        Document context


📈 Detailed Statistics:

1️⃣ TokenChunker:
   - Most consistent chunk sizes (target: 512 tokens)
   - Min tokens: 73
   - Max tokens: 512

2️⃣ SentenceChunker:
   - Preserves sentence boundaries
   - Variable chunk sizes based on sentence length
   - Min tokens: 234
   - Max tokens: 490

3️⃣ RecursiveChunker:
   - Hierarchical splitting approach
   - Respects paragraph and sentence structure
   - Min tokens: 72
   - Max tokens: 504

4️⃣ Seman

---

# 🎯 Choosing the Right Chunker: Decision Guide

```mermaid
%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#3498db', 'primaryTextColor': '#fff', 'primaryBorderColor': '#2980b9', 'lineColor': '#e74c3c', 'secondaryColor': '#2ecc71', 'tertiaryColor': '#f39c12'}}}%%
graph TD
    A[What's your use case?] --> B{Text Type?}
    
    B -->|Source Code| C[💻 CodeChunker]
    B -->|Natural Language| D{Priority?}
    
    D -->|Simple & Fast| E[🔢 TokenChunker]
    D -->|Preserve Sentences| F[📄 SentenceChunker]
    D -->|Document Structure| G[🔄 RecursiveChunker]
    D -->|Semantic Coherence| H[🧠 SemanticChunker]
    D -->|RAG Performance| I[⚡ LateChunker]
    
    E --> J[✓ Fixed sizes<br/>✓ Fast processing<br/>✗ May split sentences]
    F --> K[✓ Sentence boundaries<br/>✓ Context preserved<br/>✗ Variable sizes]
    G --> L[✓ Hierarchical<br/>✓ Structure aware<br/>~ Medium speed]
    H --> M[✓ Topic coherent<br/>✓ Smart grouping<br/>✗ Slower processing]
    I --> N[✓ Rich context<br/>✓ Best retrieval<br/>✗ Slowest]
    C --> O[✓ Syntax aware<br/>✓ Multi-language<br/>✓ AST-based]
    
    style A fill:#e74c3c,stroke:#c0392b,stroke-width:3px,color:#fff
    style B fill:#3498db,stroke:#2980b9,stroke-width:2px,color:#fff
    style D fill:#3498db,stroke:#2980b9,stroke-width:2px,color:#fff
    style E fill:#1abc9c,stroke:#16a085,stroke-width:2px,color:#fff
    style F fill:#9b59b6,stroke:#8e44ad,stroke-width:2px,color:#fff
    style G fill:#e67e22,stroke:#d35400,stroke-width:2px,color:#fff
    style H fill:#f39c12,stroke:#e67e22,stroke-width:2px
    style I fill:#2ecc71,stroke:#27ae60,stroke-width:2px,color:#fff
    style C fill:#34495e,stroke:#2c3e50,stroke-width:2px,color:#fff
```

## 📋 Quick Reference Table

| Chunker | Best For | Speed | Semantic Awareness | Embedding Support |
|---------|----------|-------|-------------------|-------------------|
| **TokenChunker** | Fixed-size requirements, API limits | ⚡⚡⚡ Very Fast | ❌ Low | ➖ N/A |
| **SentenceChunker** | Q&A, semantic completeness | ⚡⚡⚡ Very Fast | ⚠️ Medium | ➖ N/A |
| **RecursiveChunker** | Structured documents, markdown | ⚡⚡ Fast | ⚠️ Medium | ➖ N/A |
| **SemanticChunker** | Topic-based retrieval, coherence | ⚡ Moderate | ✅ High | ✅ Yes |
| **LateChunker** | Advanced RAG, best retrieval | 🐌 Slower | ✅ Very High | ✅ Yes (contextual) |
| **CodeChunker** | Source code, syntax preservation | ⚡⚡ Fast | ⚠️ Structure-aware | ➖ N/A |

## 💡 Pro Tips

### For RAG Applications:
- **SemanticChunker**: Best for topic-based retrieval and when semantic coherence matters
- **LateChunker**: Best for highest retrieval accuracy, use when performance isn't critical
- **SentenceChunker**: Good balance of speed and context preservation

### For Production Systems:
- **TokenChunker**: Most predictable, great for scaling
- **RecursiveChunker**: Good for structured content with clear hierarchy
- Use smaller `chunk_size` for more precise retrieval, larger for more context

### For Code Documentation:
- **CodeChunker**: Only choice for respecting code syntax
- Set smaller chunk_size (256-512) to keep functions/classes together

---

# 🔬 Advanced: Customizing Chunker Parameters

Let's explore how different parameters affect chunking behavior.

In [43]:
## Experiment: Effect of Different Thresholds on SemanticChunker

test_text = sample_text[:2000]  # Use first 2000 chars for quick testing

print("🧪 Testing SemanticChunker with different similarity thresholds:\n")

thresholds = [0.5, 0.7, 0.9]
results = []

for threshold in thresholds:
    chunker = SemanticChunker(
        embedding_model="minishlab/potion-base-32M",
        threshold=threshold,
        chunk_size=512
    )
    chunks = chunker.chunk(test_text)
    
    avg_tokens = sum(c.token_count for c in chunks) / len(chunks)
    results.append({
        'Threshold': threshold,
        'Total Chunks': len(chunks),
        'Avg Tokens': round(avg_tokens, 1),
        'Description': 'Larger, diverse chunks' if threshold < 0.6 else 
                       'Balanced grouping' if threshold < 0.8 else 
                       'Smaller, very similar chunks'
    })
    
    print(f"Threshold {threshold}:")
    print(f"  → {len(chunks)} chunks created")
    print(f"  → Average {avg_tokens:.1f} tokens per chunk")
    print(f"  → {results[-1]['Description']}\n")

df_results = pd.DataFrame(results)
print("\n📊 Summary Table:")
print(df_results.to_string(index=False))

print("\n💡 Insight: Lower threshold → Fewer, larger chunks (more diverse content)")
print("           Higher threshold → More, smaller chunks (very similar content)")

🧪 Testing SemanticChunker with different similarity thresholds:

Threshold 0.5:
  → 5 chunks created
  → Average 60.2 tokens per chunk
  → Larger, diverse chunks

Threshold 0.7:
  → 6 chunks created
  → Average 50.2 tokens per chunk
  → Balanced grouping

Threshold 0.9:
  → 8 chunks created
  → Average 37.6 tokens per chunk
  → Smaller, very similar chunks


📊 Summary Table:
 Threshold  Total Chunks  Avg Tokens                  Description
       0.5             5        60.2       Larger, diverse chunks
       0.7             6        50.2            Balanced grouping
       0.9             8        37.6 Smaller, very similar chunks

💡 Insight: Lower threshold → Fewer, larger chunks (more diverse content)
           Higher threshold → More, smaller chunks (very similar content)


## Experiment: Effect of Chunk Size

In [44]:
print("🧪 Testing TokenChunker with different chunk sizes:\n")

chunk_sizes = [256, 512, 1024]
size_results = []

for size in chunk_sizes:
    chunker = TokenChunker(
        tokenizer="gpt2",
        chunk_size=size,
        chunk_overlap=50
    )
    chunks = chunker.chunk(sample_text)
    
    size_results.append({
        'Chunk Size': size,
        'Total Chunks': len(chunks),
        'Avg Tokens': round(sum(c.token_count for c in chunks) / len(chunks), 1)
    })
    
    print(f"Chunk Size {size}:")
    print(f"  → {len(chunks)} chunks created")
    print(f"  → Smaller chunks = More granular retrieval")
    print(f"  → Larger chunks = More context per chunk\n")

df_size = pd.DataFrame(size_results)
print("📊 Summary Table:")
print(df_size.to_string(index=False))

print("\n💡 Choosing chunk size:")
print("   • 128-256: High precision retrieval, less context")
print("   • 512: Balanced (recommended for most use cases)")
print("   • 1024+: Maximum context, lower precision")

🧪 Testing TokenChunker with different chunk sizes:

Chunk Size 256:
  → 16 chunks created
  → Smaller chunks = More granular retrieval
  → Larger chunks = More context per chunk

Chunk Size 512:
  → 8 chunks created
  → Smaller chunks = More granular retrieval
  → Larger chunks = More context per chunk

Chunk Size 1024:
  → 4 chunks created
  → Smaller chunks = More granular retrieval
  → Larger chunks = More context per chunk

📊 Summary Table:
 Chunk Size  Total Chunks  Avg Tokens
        256            16       253.6
        512             8       457.1
       1024             4       864.2

💡 Choosing chunk size:
   • 128-256: High precision retrieval, less context
   • 512: Balanced (recommended for most use cases)
   • 1024+: Maximum context, lower precision


---

# 🎨 Visual Comparison: Side-by-Side Chunk Visualization

Let's visualize how different chunkers split the same paragraph.

In [45]:
# Extract a specific paragraph for detailed comparison
comparison_text = """
The field of artificial intelligence has undergone tremendous transformation in recent years. Machine learning algorithms have become increasingly sophisticated, enabling computers to perform tasks that once seemed exclusively human. Deep learning, a subset of machine learning, uses neural networks with multiple layers to process complex patterns in data. These networks can recognize images, understand natural language, and even generate creative content. The impact of AI extends across multiple industries. In healthcare, machine learning models can diagnose diseases from medical images with accuracy rivaling expert physicians.
"""

# Small chunk size for detailed comparison
chunk_size_compare = 200

print("🎨 Comparing chunking strategies on the same paragraph:\n")
print("=" * 80)

# TokenChunker
tc = TokenChunker(tokenizer="gpt2", chunk_size=chunk_size_compare, chunk_overlap=0)
tc_chunks = tc.chunk(comparison_text)
print(f"\n🔢 TokenChunker: {len(tc_chunks)} chunks")
for i, chunk in enumerate(tc_chunks):
    print(f"   Chunk {i+1}: '{chunk.text[:80]}...'")

# SentenceChunker  
sc = SentenceChunker(tokenizer="gpt2", chunk_size=chunk_size_compare, chunk_overlap=0)
sc_chunks = sc.chunk(comparison_text)
print(f"\n📄 SentenceChunker: {len(sc_chunks)} chunks")
for i, chunk in enumerate(sc_chunks):
    print(f"   Chunk {i+1}: '{chunk.text[:80]}...'")

# SemanticChunker
semc = SemanticChunker(
    embedding_model="minishlab/potion-base-32M",
    threshold=0.7,
    chunk_size=chunk_size_compare
)
semc_chunks = semc.chunk(comparison_text)
print(f"\n🧠 SemanticChunker: {len(semc_chunks)} chunks")
for i, chunk in enumerate(semc_chunks):
    print(f"   Chunk {i+1}: '{chunk.text[:80]}...'")

print("\n" + "=" * 80)
print("\n💡 Observations:")
print("   • TokenChunker: May split mid-sentence for fixed size")
print("   • SentenceChunker: Always keeps sentences complete")
print("   • SemanticChunker: Groups semantically related sentences together")

🎨 Comparing chunking strategies on the same paragraph:


🔢 TokenChunker: 1 chunks
   Chunk 1: '
The field of artificial intelligence has undergone tremendous transformation in...'

📄 SentenceChunker: 1 chunks
   Chunk 1: '
The field of artificial intelligence has undergone tremendous transformation in...'

🧠 SemanticChunker: 1 chunks
   Chunk 1: '
The field of artificial intelligence has undergone tremendous transformation in...'


💡 Observations:
   • TokenChunker: May split mid-sentence for fixed size
   • SentenceChunker: Always keeps sentences complete
   • SemanticChunker: Groups semantically related sentences together


---

# 🎓 Conclusion and Best Practices

## Key Takeaways

1. **Different chunkers for different needs**: No one-size-fits-all solution exists. Choose based on your specific requirements.

2. **Semantic chunkers are powerful**: SemanticChunker and LateChunker provide superior context preservation at the cost of processing speed.

3. **Token size matters**: Smaller chunks = more precise retrieval, larger chunks = more context per chunk.

4. **Code requires special handling**: Always use CodeChunker for source code to respect syntax and structure.

5. **Overlap helps continuity**: Using chunk_overlap prevents information loss at boundaries.

## Recommended Workflows

### For RAG Applications:
```python
# High accuracy, slower
chunker = SemanticChunker(threshold=0.7, chunk_size=512)

# Best retrieval performance
chunker = LateChunker(chunk_size=512)

# Fast and reliable
chunker = SentenceChunker(chunk_size=512, chunk_overlap=50)
```

### For Production Systems:
```python
# Predictable and scalable
chunker = TokenChunker(chunk_size=512, chunk_overlap=50)

# Structured documents
chunker = RecursiveChunker.from_recipe("markdown")
```

### For Code Documentation:
```python
# Python code
chunker = CodeChunker(language="python", chunk_size=256)

# JavaScript code
chunker = CodeChunker(language="javascript", chunk_size=256)
```

## 🚀 Next Steps

- Experiment with different chunk sizes and overlap values
- Test multiple chunkers on your specific dataset
- Combine chunking with Chonkie's refineries for enhanced embeddings
- Integrate with vector databases using Chonkie's handshakes
- Explore Chonkie's visualization tools for debugging

## 📚 Resources

- [Chonkie Documentation](https://docs.chonkie.ai/)
- [GitHub Repository](https://github.com/chonkie-inc/chonkie)
- [Late Chunking Paper](https://arxiv.org/abs/2409.04701)
- [Chonkie Discord Community](https://discord.com/invite/Q6zkP8w6ur)

---

**Happy Chunking! 🦛✨**